dataset:
  dataset_name: "C:/Users/sadhanas/Downloads/archive.zip"
  output_dir: "artifacts/dataset"

model:
  input_shape: [100, 100, 1]
  parallel_kernels: [3, 5, 7]
  conv2d_filters: [128, 64, 32]
  conv2d_kernel_size: [3, 3]
  pool_size: [2, 2]
  dense_units: [128, 64]
  dropout_rate: 0.5
  output_units: 2
  output_activation: "softmax"

training:
  data_path: 'artifacts\dataset\Data\train'
  feature_path: "data.npy"
  target_path: "target.npy"
  test_size: 0.1
  epoch: 1
  validation_split: 0.1
  loss: "categorical_crossentropy"
  optimizer: "adam"
  metrics: ["accuracy"]
  model_save_path: "artifacts/model/model.h5"

evaluation:
  mlflow_tracking_uri: "https://dagshub.com/sadhansd/Covid19_detection_using_AmazonSagemaker---Copy.mlflow"
